# Generated by Django 3.0.8 on 2020-07-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_number', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('use_date', models.DateTimeField(max_length=30, null=True)),
                ('used', models.BooleanField(default=False)),
                ('usage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BookStore')),
            ],
        ),
    ]
